# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
ko:
  languageCode: ko-kr

# Secondary language(English)
en:
  languageCode: en-us
  contentDir: content/en
  title: "English site title"
  params:
    description: "Site description in English."
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
